name: Ria Loader Author
favicon: null
layout_spectrum: 0.6958974914159626
typography_spectrum: 0.9967110354918987
title: Author of whimsical stories about magic and meaning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f451f'
    - '#9eae8b'
    - '#c4cdb6'
    - '#587049'
  brandStrength: 0.75
  lightness: 0.24875397491268814
  saturation: 0.5
  rhythmicContrast: 0.668606937630102
purpose: []
